name: 'Slack Notify with Thread'
description: 'Send Slack messages (with attachments) to a thread using Incoming Webhook'

inputs:
  webhook_url:
    description: 'Slack Incoming Webhook URL'
    required: true
  thread_ts:
    description: 'Thread TS (optional)'
    required: false
  pretext:
    description: 'Pretext text above the main attachment'
    required: false
    default: ''
  author_name:
    description: 'Author name'
    required: true
  repository:
    description: 'Repository link'
    required: true
  message:
    description: 'Message text content'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "Generating Slack payload..."
        TS=$(date +%s)

        THREAD_TS_LINE=""
        if [ -n "${{ inputs.thread_ts }}" ]; then
          THREAD_TS_LINE="\"thread_ts\": \"${{ inputs.thread_ts }}\","
        fi

        PRETEXT_TEXT="${{ inputs.pretext }}"
        if [ -z "$PRETEXT_TEXT" ]; then
          PRETEXT_TEXT="通知があります"
        fi

        ESCAPED_MESSAGE=$(echo "${{ inputs.message }}" | sed 's/"/\\"/g')

        cat <<EOF > payload.json
        {
          "channel": "dev-インターン_ハンズオン",
          $THREAD_TS_LINE
          "attachments": [
            {
              "fallback": "ハンズオンの通知",
              "color": "#215EBF",
              "pretext": "$PRETEXT_TEXT",
              "author_name": "${{ inputs.author_name }}",
              "title": "GitHub Repository",
              "title_link": "${{ inputs.repository }}",
              "text": "$ESCAPED_MESSAGE",
              "footer": "インターン_ハンズオン BOT",
              "footer_icon": "https://qiita-user-contents.imgix.net/https%3A%2F%2Fqiita-image-store.s3.ap-northeast-1.amazonaws.com%2F0%2F1022001%2F30818b78-45d7-bac7-12b9-8433c2ef3011.png?ixlib=rb-4.0.0&auto=format&gif-q=60&q=75&s=035dfbe9921b278308e895b5e03dab1a",
              "ts": $TS
            }
          ]
        }
        EOF
        echo "Posting to Slack..."
        if curl --fail --show-error -X POST -H 'Content-type: application/json' --data @payload.json https://github.com/ippanpeople/sacloud-apprun-action/blob/master/action.yaml; then
          echo "🚀 Slack 通知成功"
        else
          echo "❌ Slack 通知失敗"
          exit 1
        fi
